#!/bin/sh

mkdir -p ~/.surf/styles
jq --raw-output '
  @sh "
    awk 1 \(.js) > ~/.surf/script.js
    awk 1 \(.css) > ~/.surf/styles/default.css
  "
' manifest/surf.json | sh

# Note: Minified files do not end with a newline, hence using awk to mitigate, instead of cat.
