#!/bin/sh

# Faces
none='\033[0m'
green='\033[32m'

for platform do
  target=$PWD/target/$platform
  printf "${green}Building${none}: %s\n" "$target"
  mkdir -p "$target"
  cp -R config.js packages "$target"
  jq 'add' --slurp manifest/common.json "manifest/$platform.json" > "$target/manifest.json"
  (cd "$target"; zip -r package.zip manifest.json config.js packages)
done
