#!/bin/sh

mkdir -p website/packages
cd website/packages
../../scripts/fetch .
cp ../../src/krabby/web/krabby.js .
cp ../../src/krabby/web/krabby.css .
curl -sSL -O https://github.com/alexherbo2/carousel.js/raw/master/src/carousel.js
curl -sSL https://github.com/alexherbo2/krabby-resources/raw/master/introduction/subs/2020-05-25_10:36:39.vtt --create-dirs -o introduction/subs/2020-05-25_10:36:39.vtt
