#!/bin/sh

# Faces
none=$(printf '\033[0m')
green=$(printf '\033[32m')

curl() {
  command curl --silent --show-error --location "$@" \
    --write-out "${green}Fetching${none}: %{url_effective} → ${PWD}/%{filename_effective}\n"
}

fetch() {
  case $# in
    1) curl --remote-name "$1" ;;
    2) curl "$1" --output "$2" ;;
  esac
}

fetch https://github.com/alexherbo2/modal.js/raw/master/scripts/modal.js
fetch https://github.com/alexherbo2/prompt.js/raw/master/scripts/prompt.js
fetch https://github.com/alexherbo2/hint.js/raw/master/scripts/hint.js
fetch https://github.com/alexherbo2/selection.js/raw/master/scripts/selection.js
fetch https://github.com/alexherbo2/selection.js/raw/master/styles/selection.css
fetch https://github.com/alexherbo2/mouse.js/raw/master/scripts/mouse.js
fetch https://github.com/alexherbo2/clipboard.js/raw/master/scripts/clipboard.js
fetch https://github.com/alexherbo2/scroll.js/raw/master/scripts/scroll.js
fetch https://github.com/alexherbo2/player.js/raw/master/scripts/player.js
fetch https://iconfinder.com/icons/877852/download/svg/512 krabby.svg
fetch https://iconfinder.com/icons/877852/download/png/512 krabby.png
