#!/bin/sh

# Base directory
packages=${1:-packages}

# Faces
none=$(printf '\033[0m')
green=$(printf '\033[32m')

curl() {
  command curl --silent --show-error --location "$@" \
    --write-out "${green}Fetching${none}: %{url_effective} → ${PWD}/%{filename_effective}\n"
}

fetch() {
  case $# in
    1) curl --remote-name "$1" ;;
    2) curl "$1" --output "$2" ;;
  esac
}

# Ensure the base directory exists
mkdir -p "$packages"
cd "$packages"

fetch https://github.com/alexherbo2/modal.js/raw/master/src/modal.js
fetch https://cdn.jsdelivr.net/npm/@simonwep/selection-js/dist/selection.min.js mouse-selection.js
fetch https://github.com/alexherbo2/prompt.js/raw/master/src/prompt.js
fetch https://github.com/alexherbo2/hint.js/raw/master/src/hint.js
fetch https://github.com/alexherbo2/mark.js/raw/master/src/mark.js
fetch https://github.com/alexherbo2/selection.js/raw/master/src/selection.js
fetch https://github.com/alexherbo2/selection.js/raw/master/src/selection.css
fetch https://github.com/alexherbo2/mouse.js/raw/master/src/mouse.js
fetch https://github.com/alexherbo2/clipboard.js/raw/master/src/clipboard.js
fetch https://github.com/alexherbo2/scroll.js/raw/master/src/scroll.js
fetch https://github.com/alexherbo2/player.js/raw/master/src/player.js
fetch https://iconfinder.com/icons/877852/download/svg/512 krabby.svg
fetch https://iconfinder.com/icons/877852/download/png/512 krabby.png
